// Generated by CoffeeScript 1.6.2
var WebSocketServer, app, center, chokidar, client, events, filename, fs, http, log, options, path, watch_files, wss, _ref;

fs = require('fs');

http = require('http');

path = require('path');

chokidar = require("chokidar");

events = require("events");

log = function() {};

center = new events.EventEmitter;

watch_files = [];

options = {};

process.argv.slice(2).forEach(function(string) {
  var key, value, _ref;

  if (string.match(/\S:\S/)) {
    _ref = string.split(":"), key = _ref[0], value = _ref[1];
    return options[key] = value;
  } else {
    return watch_files.push(string);
  }
});

if ((_ref = options.log) === "true" || _ref === "yes" || _ref === "on") {
  log = console.log;
}

if (options.ws != null) {
  options.ws = Number(options.ws);
}

if (options.port != null) {
  options.port = Number(options.port);
}

if ((options.port != null) && (options.ws == null)) {
  options.ws = options.port - 1;
}

log("options:", options);

log("watching:", watch_files);

WebSocketServer = require('ws').Server;

wss = new WebSocketServer({
  port: options.ws || 7776,
  host: '0.0.0.0'
});

wss.on('connection', function(ws) {
  var notify;

  notify = function() {
    try {
      return ws.send("reload");
    } catch (_error) {}
  };
  center.on("update", notify);
  return ws.on('close', function() {
    return center.removeListener("update", notify);
  });
});

filename = path.join(__dirname, "doodle.js");

client = fs.readFileSync(filename, "utf8");

if (options.ws != null) {
  client = client.replace(/7776/, options.ws);
}

app = http.createServer(function(req, res) {
  res.writeHead(200, {
    'Content-Type': 'text/javascript'
  });
  return res.end(client);
});

app.listen(options.port || 7777);

watch_files.forEach(function(file) {
  var watcher;

  watcher = chokidar.watch(file);
  return watcher.on("change", function(path) {
    center.emit("update");
    return log("Update from:", path);
  });
});
