// Generated by CoffeeScript 1.4.0
(function() {
  var WebSocketServer, app, delay, fs, here, http, make, path, repeat, show, time, watchDir, watchFile, watchPath, wss;

  fs = require('fs');

  http = require('http');

  path = require('path');

  show = function() {};

  repeat = function(t, f) {
    return setInterval(f, t);
  };

  delay = function(t, f) {
    return setTimeout(f, t);
  };

  make = function() {
    var ret;
    ret = new Date().getTime().toString();
    show(ret.slice(8), '&doodle');
    return ret;
  };

  time = make();

  WebSocketServer = require('ws').Server;

  wss = new WebSocketServer({
    port: 7776,
    host: '0.0.0.0'
  });

  wss.on('connection', function(ws) {
    var me, record;
    show('connection');
    record = time;
    me = repeat(200, function() {
      show(time, record, typeof time, typeof record);
      if (time !== record) {
        show('reload...');
        record = time;
        try {
          return ws.send('reload');
        } catch (err) {
          return show('already closed');
        }
      }
    });
    return ws.on('close', function() {
      clearInterval(me);
      return show('close');
    });
  });

  watchFile = function(name) {
    var op;
    show('watch: ', name);
    op = {
      interval: 300
    };
    return fs.watchFile(name, op, function() {
      return time = make();
    });
  };

  watchDir = function(name) {
    var list;
    list = fs.readdirSync(name);
    return list.forEach(function(item) {
      if (item[0] !== '.') {
        return watchPath(path.join(name, item));
      }
    });
  };

  watchPath = function(name) {
    var stat;
    stat = fs.statSync(name);
    if (stat.isDirectory()) {
      return watchDir(name);
    } else if (stat.isFile()) {
      return watchFile(name);
    } else {
      return show('unkown file:', name);
    }
  };

  here = process.env.PWD;

  process.argv.slice(2).forEach(function(name) {
    if ((name[0] != null) && (name[0] === '/')) {
      return watchPath(name);
    } else {
      return watchPath(path.join(here, name));
    }
  });

  app = http.createServer(function(req, res) {
    var filepath;
    if (req.url === '/doodle.js') {
      res.writeHead(200, {
        'Content-Type': 'text/javascript'
      });
      filepath = path.join(__dirname, 'doodle.js');
      return fs.readFile(filepath, 'utf-8', function(err, data) {
        if (err != null) {
          show(err);
        }
        return res.end(data);
      });
    }
  });

  app.listen(7777);

}).call(this);
