// Generated by CoffeeScript 1.3.3
(function() {
  var delay, hostname, ws;

  hostname = location.hostname;

  ws = new WebSocket("ws://" + hostname + ":7776");

  ws.onmessage = function(message) {
    console.log('message');
    if (message.data === 'reload') {
      return location.reload();
    }
  };

  delay = function(t, f) {
    return setTimeout(f, t);
  };

  ws.onclose = function() {
    return delay(1000, location.reload());
  };

}).call(this);
